// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: apps.sql

package persistence

import (
	"context"
	"database/sql"
)

const createApp = `-- name: CreateApp :exec
INSERT INTO apps (id, schema, date_added, client_id, client_secret)
VALUES (?1, jsonb(?2), unixepoch(), ?3, ?4)
`

type CreateAppParams struct {
	ID           string
	Schema       interface{}
	ClientID     sql.NullString
	ClientSecret sql.NullString
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) error {
	_, err := q.db.ExecContext(ctx, createApp,
		arg.ID,
		arg.Schema,
		arg.ClientID,
		arg.ClientSecret,
	)
	return err
}

const removeApp = `-- name: RemoveApp :execresult
DELETE FROM apps where id = ?
`

func (q *Queries) RemoveApp(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeApp, id)
}

const updateApp = `-- name: UpdateApp :exec
UPDATE apps SET schema = jsonb(?1)
WHERE id = ?2
`

type UpdateAppParams struct {
	Schema interface{}
	ID     string
}

func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) error {
	_, err := q.db.ExecContext(ctx, updateApp, arg.Schema, arg.ID)
	return err
}
