// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package persistence

import (
	"database/sql"
	"time"
)

type App struct {
	ID           string         `json:"id"`
	Schema       []byte         `json:"schema"`
	DateAdded    int64          `json:"date_added"`
	ClientID     sql.NullString `json:"client_id"`
	ClientSecret sql.NullString `json:"client_secret"`
	Status       string         `json:"status"`
}

type InviteCode struct {
	Code       string    `json:"code"`
	ExpiryDate time.Time `json:"expiry_date"`
	Roles      []byte    `json:"roles"`
}

type PackageCategory struct {
	Category string `json:"category"`
}

type PackageCategoryDefinition struct {
	PackageID string `json:"package_id"`
	Category  string `json:"category"`
}

type PackageListItem struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Version     string `json:"version"`
	Author      string `json:"author"`
	Description string `json:"description"`
	ImageUrl    string `json:"image_url"`
}

type UserOption struct {
	UserID           string `json:"user_id"`
	CompletedWelcome bool   `json:"completed_welcome"`
}
