// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package persistence

import (
	"database/sql"
)

type App struct {
	ID           string
	Schema       []byte
	DateAdded    int64
	ClientID     sql.NullString
	ClientSecret sql.NullString
}
