// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package persistence

import (
	"context"
)

const createApp = `-- name: CreateApp :exec
INSERT INTO apps (id, schema, date_added)
VALUES (?, jsonb(?), unixepoch())
`

type CreateAppParams struct {
	ID    string
	Jsonb interface{}
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) error {
	_, err := q.db.ExecContext(ctx, createApp, arg.ID, arg.Jsonb)
	return err
}

const removeApp = `-- name: RemoveApp :exec
DELETE FROM apps where id = ?
`

func (q *Queries) RemoveApp(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, removeApp, id)
	return err
}
