services:
  sqlite:
    image: busybox
    volumes:
      - hydra-sqlite:/mnt/sqlite
    command: "chmod -R 777 /mnt/sqlite"
  hydra:
    image: oryd/hydra:v2.3.0
    build:
      context: .
      dockerfile: .docker/Dockerfile-local-build
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - hydra-sqlite:/mnt/sqlite:rw
      - type: bind
        source: ./hydra.yml
        target: /etc/config/hydra/hydra.yml
    pull_policy: missing
    environment:
      - DSN=sqlite:///mnt/sqlite/db.sqlite?_fk=true&mode=rwc
    restart: unless-stopped
    depends_on:
      - hydra-migrate
      - sqlite
    networks:
      - hydranet
  hydra-migrate:
    image: oryd/hydra:v2.3.0
    build:
      context: .
      dockerfile: .docker/Dockerfile-local-build
    environment:
      - DSN=sqlite:///mnt/sqlite/db.sqlite?_fk=true&mode=rwc
    command: migrate -c /etc/config/hydra/hydra.yml sql up -e --yes
    pull_policy: missing
    volumes:
      - hydra-sqlite:/mnt/sqlite:rw
      - type: bind
        source: ./hydra.yml
        target: /etc/config/hydra/hydra.yml
    restart: on-failure
    networks:
      - hydranet
    depends_on:
      - sqlite
  consent:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    image: oryd/hydra-login-consent-node:v2.3.0
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - hydranet
networks:
  hydranet:
volumes:
  hydra-sqlite: